# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 22 Dec 2024 12:39:00 +0000
*               @ALL          1
*               @user         8
