<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sun, 22 Dec 2024 12:39:00 +0000
 */
$conf['title'] = 'EUDIGS';
$conf['lang'] = 'en';
$conf['license'] = 'gnufdl';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
