# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sun, 22 Dec 2024 12:39:00 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

admin:$2y$10$xAdfbZFkRVQuVRK5BPtzze92cGN9cwMBtpPi1e9CfbxwexoxlJ4w6:admin:admin@localhost:admin,user
